services:
  - type: web
    name: bibliotheque-fegbm
    env: python
    buildCommand: bash .buildsh
    startCommand: gunicorn wsgi:app --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PATH
        value: /usr/local/bin:/usr/bin:/bin
    disk:
      name: storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
    staticPublishPath: ./www
    routes:
      - type: rewrite
        source: /*
        destination: /index.html